version: "3.9"


# Networks
networks:
  dozzle:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: dozzle
    ipam:
      driver: default
      config:
        - subnet: ${SUBNET}/24
          gateway: ${GATEWAY}
      

services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    hostname: ${DZ_HOST}
    domainname: ${DOMAIN}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/dozzle", "healthcheck"]
      interval: 3s
      timeout: 30s
      retries: 5
      start_period: 30s
#    environment:
      # Uncomment to enable container actions (stop, start, restart). See https://dozzle.dev/guide/actions
      # - DOZZLE_ENABLE_ACTIONS=true
      #
      # Uncomment to allow access to container shells. See https://dozzle.dev/guide/shell
      # - DOZZLE_ENABLE_SHELL=true
      #
      # Uncomment to enable authentication. See https://dozzle.dev/guide/authentication
      # - DOZZLE_AUTH_PROVIDER=simple
    networks:
      dozzle:
        ipv4_address: ${DZ_IP}
    ports:
      - ${DZ_EXT_PORT}:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro