version: "3.9"

# docker managed persistent volumes
volumes:
  domotz_data:

services:
  domotz-collector:
    image: "domotz/domotz-collector"
    container_name: domotz-collector
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    environment:
      LISTEN_PORT: "3003"
    network_mode: "host"
    volumes:
      - domotz_data:/opt/domotz/etc/